version: "3.8"

services:
  sqlite-db:
    image: keinos/sqlite3
    container_name: sqlite-db
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "sqlite3", "/data/basedatos.db", ".tables"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: utec-app
    depends_on:
      sqlite-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_PATH=/data/basedatos.db
    links:
      - sqlite-db
